//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_TESTER_UI.Session {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://corridor.aero/cws/", ConfigurationName="Session.SessionSoap")]
    public interface SessionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        API_TESTER_UI.Session.LoginResponse Login(API_TESTER_UI.Session.CorridorLoginData loginData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.Session.LoginResponse> LoginAsync(API_TESTER_UI.Session.CorridorLoginData loginData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        API_TESTER_UI.Session.LogoutResponse Logout(API_TESTER_UI.Session.CorridorLogoutData logoutData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.Session.LogoutResponse> LogoutAsync(API_TESTER_UI.Session.CorridorLogoutData logoutData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorLoginData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasNameField;
        
        private string loginIDField;
        
        private string loginPasswordField;
        
        private string sessionTokenField;
        
        private string auth0TokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("AliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
                this.RaisePropertyChanged("LoginID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LoginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                this.loginPasswordField = value;
                this.RaisePropertyChanged("LoginPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("SessionToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Auth0Token {
            get {
                return this.auth0TokenField;
            }
            set {
                this.auth0TokenField = value;
                this.RaisePropertyChanged("Auth0Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorLogoutData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionTokenField;
        
        private string auth0TokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("SessionToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Auth0Token {
            get {
                return this.auth0TokenField;
            }
            set {
                this.auth0TokenField = value;
                this.RaisePropertyChanged("Auth0Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class ErrorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTextField;
        
        private int errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorStatusData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusMessageField;
        
        private ErrorMessage[] errorMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ErrorMessage[] ErrorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
                this.RaisePropertyChanged("ErrorMessages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class LogoutResponse : CorridorStatusData {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class LoginResponse : CorridorStatusData {
        
        private string sessionTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("SessionToken");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionSoapChannel : API_TESTER_UI.Session.SessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionSoapClient : System.ServiceModel.ClientBase<API_TESTER_UI.Session.SessionSoap>, API_TESTER_UI.Session.SessionSoap {
        
        public SessionSoapClient() {
        }
        
        public SessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public API_TESTER_UI.Session.LoginResponse Login(API_TESTER_UI.Session.CorridorLoginData loginData) {
            return base.Channel.Login(loginData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.Session.LoginResponse> LoginAsync(API_TESTER_UI.Session.CorridorLoginData loginData) {
            return base.Channel.LoginAsync(loginData);
        }
        
        public API_TESTER_UI.Session.LogoutResponse Logout(API_TESTER_UI.Session.CorridorLogoutData logoutData) {
            return base.Channel.Logout(logoutData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.Session.LogoutResponse> LogoutAsync(API_TESTER_UI.Session.CorridorLogoutData logoutData) {
            return base.Channel.LogoutAsync(logoutData);
        }
    }
}
