//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_TESTER_UI.UserManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://corridor.aero/cws/", ConfigurationName="UserManagement.UserManagementSoap")]
    public interface UserManagementSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/AddUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementReferenceOutput AddUser(API_TESTER_UI.UserManagement.UserManagementData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> AddUserAsync(API_TESTER_UI.UserManagement.UserManagementData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/UpdateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementReferenceOutput UpdateUser(API_TESTER_UI.UserManagement.UserManagementUpdateData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> UpdateUserAsync(API_TESTER_UI.UserManagement.UserManagementUpdateData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/AddOrEditUserRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementReferenceOutput AddOrEditUserRequest(API_TESTER_UI.UserManagement.UserManagemenAddOrUpdateData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/AddOrEditUserRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> AddOrEditUserRequestAsync(API_TESTER_UI.UserManagement.UserManagemenAddOrUpdateData userData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/GetUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementDataOutput GetUser(API_TESTER_UI.UserManagement.UserManagementReferenceInput userReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementDataOutput> GetUserAsync(API_TESTER_UI.UserManagement.UserManagementReferenceInput userReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/ChangeUserPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementReferenceOutput ChangeUserPassword(API_TESTER_UI.UserManagement.UserManagementChangePasswordInput userPasswdData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/ChangeUserPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> ChangeUserPasswordAsync(API_TESTER_UI.UserManagement.UserManagementChangePasswordInput userPasswdData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/CreatePermissionsProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorStatusData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CorridorLoginData))]
        API_TESTER_UI.UserManagement.UserManagementReferenceOutput CreatePermissionsProfile(API_TESTER_UI.UserManagement.UserManagementCreatePermissionsProfileInput userCreateProfileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://corridor.aero/cws/CreatePermissionsProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> CreatePermissionsProfileAsync(API_TESTER_UI.UserManagement.UserManagementCreatePermissionsProfileInput userCreateProfileData);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagemenAddOrUpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementUpdateData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementData : CorridorLoginData {
        
        private string usernameField;
        
        private string fullnameField;
        
        private string descriptionField;
        
        private string departmentField;
        
        private string userBadgeIDField;
        
        private string emailField;
        
        private string auth0EmailField;
        
        private string passwordField;
        
        private string accessCodeField;
        
        private string activeDirectoryNameField;
        
        private string userPermissionsProfileField;
        
        private UserDefinedField[] userDefinedFieldsField;
        
        private string defaultScreenField;
        
        private double purchaseLimitField;
        
        private double laborCostField;
        
        private double regularCostField;
        
        private double overtimeCostField;
        
        private double doubleTimeCostField;
        
        private double regularBurdenCostField;
        
        private double overtimeBurdenCostField;
        
        private double doubleTimeBurdenCostField;
        
        private string regularLaborAccountNumberField;
        
        private string overtimeLaborAccountNumberField;
        
        private string doubleTimeLaborAccountNumberField;
        
        private string laborBurdenAccountNumberField;
        
        private System.Nullable<bool> auth0RequiredField;
        
        private bool mustChangePasswordField;
        
        private bool mustChangeAccessCodeField;
        
        private bool cannotChangePasswordField;
        
        private bool accountDisabledField;
        
        private bool locatorField;
        
        private bool suspendLocatorField;
        
        private bool canSelectLocatorField;
        
        private bool canSelectToVendorLotField;
        
        private bool receivingInspectorField;
        
        private bool tipOfDayField;
        
        private bool largeButtonsField;
        
        private bool disablePersistenceField;
        
        private bool defaultIncludeFuelActivityField;
        
        private bool onlyIncludeFuelActivityField;
        
        private bool defaultIncludeServiceActivityField;
        
        private bool onlyIncludeServiceActivityField;
        
        private bool defaultIncludePartSaleActivityField;
        
        private bool onlyIncludePartSaleActivityField;
        
        private bool defaultIncludeCateringActivityField;
        
        private bool onlyIncludeCateringActivityField;
        
        private bool defaultIncludeHotelActivityField;
        
        private bool onlyIncludeHotelActivityField;
        
        private bool defaultIncludeTransportationActivityField;
        
        private bool onlyIncludeTransportationActivityField;
        
        private bool launchLogbookResearchField;
        
        private bool canEnterComplianceField;
        
        private bool includeAllDefaultLogbookSearchCriteriaField;
        
        private bool onlyDisplayAssignedInWOQMgmtField;
        
        public UserManagementData() {
            this.purchaseLimitField = -99999.99999D;
            this.laborCostField = -99999.99999D;
            this.regularCostField = -99999.99999D;
            this.overtimeCostField = -99999.99999D;
            this.doubleTimeCostField = -99999.99999D;
            this.regularBurdenCostField = -99999.99999D;
            this.overtimeBurdenCostField = -99999.99999D;
            this.doubleTimeBurdenCostField = -99999.99999D;
            this.mustChangePasswordField = false;
            this.mustChangeAccessCodeField = false;
            this.cannotChangePasswordField = false;
            this.accountDisabledField = false;
            this.locatorField = false;
            this.suspendLocatorField = false;
            this.canSelectLocatorField = false;
            this.canSelectToVendorLotField = false;
            this.receivingInspectorField = false;
            this.tipOfDayField = false;
            this.largeButtonsField = false;
            this.disablePersistenceField = false;
            this.defaultIncludeFuelActivityField = false;
            this.onlyIncludeFuelActivityField = false;
            this.defaultIncludeServiceActivityField = false;
            this.onlyIncludeServiceActivityField = false;
            this.defaultIncludePartSaleActivityField = false;
            this.onlyIncludePartSaleActivityField = false;
            this.defaultIncludeCateringActivityField = false;
            this.onlyIncludeCateringActivityField = false;
            this.defaultIncludeHotelActivityField = false;
            this.onlyIncludeHotelActivityField = false;
            this.defaultIncludeTransportationActivityField = false;
            this.onlyIncludeTransportationActivityField = false;
            this.launchLogbookResearchField = false;
            this.canEnterComplianceField = false;
            this.includeAllDefaultLogbookSearchCriteriaField = false;
            this.onlyDisplayAssignedInWOQMgmtField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
                this.RaisePropertyChanged("Fullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UserBadgeID {
            get {
                return this.userBadgeIDField;
            }
            set {
                this.userBadgeIDField = value;
                this.RaisePropertyChanged("UserBadgeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Auth0Email {
            get {
                return this.auth0EmailField;
            }
            set {
                this.auth0EmailField = value;
                this.RaisePropertyChanged("Auth0Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AccessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
                this.RaisePropertyChanged("AccessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ActiveDirectoryName {
            get {
                return this.activeDirectoryNameField;
            }
            set {
                this.activeDirectoryNameField = value;
                this.RaisePropertyChanged("ActiveDirectoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UserPermissionsProfile {
            get {
                return this.userPermissionsProfileField;
            }
            set {
                this.userPermissionsProfileField = value;
                this.RaisePropertyChanged("UserPermissionsProfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public UserDefinedField[] UserDefinedFields {
            get {
                return this.userDefinedFieldsField;
            }
            set {
                this.userDefinedFieldsField = value;
                this.RaisePropertyChanged("UserDefinedFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DefaultScreen {
            get {
                return this.defaultScreenField;
            }
            set {
                this.defaultScreenField = value;
                this.RaisePropertyChanged("DefaultScreen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double PurchaseLimit {
            get {
                return this.purchaseLimitField;
            }
            set {
                this.purchaseLimitField = value;
                this.RaisePropertyChanged("PurchaseLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double LaborCost {
            get {
                return this.laborCostField;
            }
            set {
                this.laborCostField = value;
                this.RaisePropertyChanged("LaborCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double RegularCost {
            get {
                return this.regularCostField;
            }
            set {
                this.regularCostField = value;
                this.RaisePropertyChanged("RegularCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double OvertimeCost {
            get {
                return this.overtimeCostField;
            }
            set {
                this.overtimeCostField = value;
                this.RaisePropertyChanged("OvertimeCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double DoubleTimeCost {
            get {
                return this.doubleTimeCostField;
            }
            set {
                this.doubleTimeCostField = value;
                this.RaisePropertyChanged("DoubleTimeCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double RegularBurdenCost {
            get {
                return this.regularBurdenCostField;
            }
            set {
                this.regularBurdenCostField = value;
                this.RaisePropertyChanged("RegularBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double OvertimeBurdenCost {
            get {
                return this.overtimeBurdenCostField;
            }
            set {
                this.overtimeBurdenCostField = value;
                this.RaisePropertyChanged("OvertimeBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double DoubleTimeBurdenCost {
            get {
                return this.doubleTimeBurdenCostField;
            }
            set {
                this.doubleTimeBurdenCostField = value;
                this.RaisePropertyChanged("DoubleTimeBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string RegularLaborAccountNumber {
            get {
                return this.regularLaborAccountNumberField;
            }
            set {
                this.regularLaborAccountNumberField = value;
                this.RaisePropertyChanged("RegularLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OvertimeLaborAccountNumber {
            get {
                return this.overtimeLaborAccountNumberField;
            }
            set {
                this.overtimeLaborAccountNumberField = value;
                this.RaisePropertyChanged("OvertimeLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DoubleTimeLaborAccountNumber {
            get {
                return this.doubleTimeLaborAccountNumberField;
            }
            set {
                this.doubleTimeLaborAccountNumberField = value;
                this.RaisePropertyChanged("DoubleTimeLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string LaborBurdenAccountNumber {
            get {
                return this.laborBurdenAccountNumberField;
            }
            set {
                this.laborBurdenAccountNumberField = value;
                this.RaisePropertyChanged("LaborBurdenAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<bool> Auth0Required {
            get {
                return this.auth0RequiredField;
            }
            set {
                this.auth0RequiredField = value;
                this.RaisePropertyChanged("Auth0Required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
                this.RaisePropertyChanged("MustChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustChangeAccessCode {
            get {
                return this.mustChangeAccessCodeField;
            }
            set {
                this.mustChangeAccessCodeField = value;
                this.RaisePropertyChanged("MustChangeAccessCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CannotChangePassword {
            get {
                return this.cannotChangePasswordField;
            }
            set {
                this.cannotChangePasswordField = value;
                this.RaisePropertyChanged("CannotChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AccountDisabled {
            get {
                return this.accountDisabledField;
            }
            set {
                this.accountDisabledField = value;
                this.RaisePropertyChanged("AccountDisabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Locator {
            get {
                return this.locatorField;
            }
            set {
                this.locatorField = value;
                this.RaisePropertyChanged("Locator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuspendLocator {
            get {
                return this.suspendLocatorField;
            }
            set {
                this.suspendLocatorField = value;
                this.RaisePropertyChanged("SuspendLocator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanSelectLocator {
            get {
                return this.canSelectLocatorField;
            }
            set {
                this.canSelectLocatorField = value;
                this.RaisePropertyChanged("CanSelectLocator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanSelectToVendorLot {
            get {
                return this.canSelectToVendorLotField;
            }
            set {
                this.canSelectToVendorLotField = value;
                this.RaisePropertyChanged("CanSelectToVendorLot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReceivingInspector {
            get {
                return this.receivingInspectorField;
            }
            set {
                this.receivingInspectorField = value;
                this.RaisePropertyChanged("ReceivingInspector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TipOfDay {
            get {
                return this.tipOfDayField;
            }
            set {
                this.tipOfDayField = value;
                this.RaisePropertyChanged("TipOfDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LargeButtons {
            get {
                return this.largeButtonsField;
            }
            set {
                this.largeButtonsField = value;
                this.RaisePropertyChanged("LargeButtons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisablePersistence {
            get {
                return this.disablePersistenceField;
            }
            set {
                this.disablePersistenceField = value;
                this.RaisePropertyChanged("DisablePersistence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeFuelActivity {
            get {
                return this.defaultIncludeFuelActivityField;
            }
            set {
                this.defaultIncludeFuelActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeFuelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeFuelActivity {
            get {
                return this.onlyIncludeFuelActivityField;
            }
            set {
                this.onlyIncludeFuelActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeFuelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeServiceActivity {
            get {
                return this.defaultIncludeServiceActivityField;
            }
            set {
                this.defaultIncludeServiceActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeServiceActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeServiceActivity {
            get {
                return this.onlyIncludeServiceActivityField;
            }
            set {
                this.onlyIncludeServiceActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeServiceActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludePartSaleActivity {
            get {
                return this.defaultIncludePartSaleActivityField;
            }
            set {
                this.defaultIncludePartSaleActivityField = value;
                this.RaisePropertyChanged("DefaultIncludePartSaleActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludePartSaleActivity {
            get {
                return this.onlyIncludePartSaleActivityField;
            }
            set {
                this.onlyIncludePartSaleActivityField = value;
                this.RaisePropertyChanged("OnlyIncludePartSaleActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeCateringActivity {
            get {
                return this.defaultIncludeCateringActivityField;
            }
            set {
                this.defaultIncludeCateringActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeCateringActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeCateringActivity {
            get {
                return this.onlyIncludeCateringActivityField;
            }
            set {
                this.onlyIncludeCateringActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeCateringActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeHotelActivity {
            get {
                return this.defaultIncludeHotelActivityField;
            }
            set {
                this.defaultIncludeHotelActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeHotelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeHotelActivity {
            get {
                return this.onlyIncludeHotelActivityField;
            }
            set {
                this.onlyIncludeHotelActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeHotelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeTransportationActivity {
            get {
                return this.defaultIncludeTransportationActivityField;
            }
            set {
                this.defaultIncludeTransportationActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeTransportationActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeTransportationActivity {
            get {
                return this.onlyIncludeTransportationActivityField;
            }
            set {
                this.onlyIncludeTransportationActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeTransportationActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LaunchLogbookResearch {
            get {
                return this.launchLogbookResearchField;
            }
            set {
                this.launchLogbookResearchField = value;
                this.RaisePropertyChanged("LaunchLogbookResearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanEnterCompliance {
            get {
                return this.canEnterComplianceField;
            }
            set {
                this.canEnterComplianceField = value;
                this.RaisePropertyChanged("CanEnterCompliance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeAllDefaultLogbookSearchCriteria {
            get {
                return this.includeAllDefaultLogbookSearchCriteriaField;
            }
            set {
                this.includeAllDefaultLogbookSearchCriteriaField = value;
                this.RaisePropertyChanged("IncludeAllDefaultLogbookSearchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyDisplayAssignedInWOQMgmt {
            get {
                return this.onlyDisplayAssignedInWOQMgmtField;
            }
            set {
                this.onlyDisplayAssignedInWOQMgmtField = value;
                this.RaisePropertyChanged("OnlyDisplayAssignedInWOQMgmt");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserDefinedField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("Label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class ErrorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorTextField;
        
        private int errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementDataOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementReferenceOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorStatusData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusMessageField;
        
        private ErrorMessage[] errorMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ErrorMessage[] ErrorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
                this.RaisePropertyChanged("ErrorMessages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementDataOutput : CorridorStatusData {
        
        private string usernameField;
        
        private long userKeyField;
        
        private string purchaseLimitField;
        
        private string regularCostField;
        
        private string overtimeCostField;
        
        private string doubleTimeCostField;
        
        private string regularBurdenCostField;
        
        private string overtimeBurdenCostField;
        
        private string doubleTimeBurdenCostField;
        
        private string fullnameField;
        
        private string descriptionField;
        
        private string departmentField;
        
        private string userBadgeIDField;
        
        private string emailField;
        
        private string auth0EmailField;
        
        private bool auth0RequiredField;
        
        private string activeDirectoryNameField;
        
        private string userPermissionsProfileField;
        
        private UserDefinedField[] userDefinedFieldsField;
        
        private string regularLaborAccountNumberField;
        
        private string overtimeLaborAccountNumberField;
        
        private string doubleTimeLaborAccountNumberField;
        
        private string laborBurdenAccountNumberField;
        
        private string defaultScreenField;
        
        private bool mustChangePasswordField;
        
        private bool cannotChangePasswordField;
        
        private bool accountDisabledField;
        
        private bool locatorField;
        
        private bool suspendLocatorField;
        
        private bool canSelectLocatorField;
        
        private bool canSelectToVendorLotField;
        
        private bool receivingInspectorField;
        
        private bool tipOfDayField;
        
        private bool largeButtonsField;
        
        private bool disablePersistenceField;
        
        private bool defaultIncludeFuelActivityField;
        
        private bool onlyIncludeFuelActivityField;
        
        private bool defaultIncludeServiceActivityField;
        
        private bool onlyIncludeServiceActivityField;
        
        private bool defaultIncludePartSaleActivityField;
        
        private bool onlyIncludePartSaleActivityField;
        
        private bool defaultIncludeCateringActivityField;
        
        private bool onlyIncludeCateringActivityField;
        
        private bool defaultIncludeHotelActivityField;
        
        private bool onlyIncludeHotelActivityField;
        
        private bool defaultIncludeTransportationActivityField;
        
        private bool onlyIncludeTransportationActivityField;
        
        private bool launchLogbookResearchField;
        
        private bool canEnterComplianceField;
        
        private bool includeAllDefaultLogbookSearchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UserKey {
            get {
                return this.userKeyField;
            }
            set {
                this.userKeyField = value;
                this.RaisePropertyChanged("UserKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PurchaseLimit {
            get {
                return this.purchaseLimitField;
            }
            set {
                this.purchaseLimitField = value;
                this.RaisePropertyChanged("PurchaseLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegularCost {
            get {
                return this.regularCostField;
            }
            set {
                this.regularCostField = value;
                this.RaisePropertyChanged("RegularCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OvertimeCost {
            get {
                return this.overtimeCostField;
            }
            set {
                this.overtimeCostField = value;
                this.RaisePropertyChanged("OvertimeCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DoubleTimeCost {
            get {
                return this.doubleTimeCostField;
            }
            set {
                this.doubleTimeCostField = value;
                this.RaisePropertyChanged("DoubleTimeCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RegularBurdenCost {
            get {
                return this.regularBurdenCostField;
            }
            set {
                this.regularBurdenCostField = value;
                this.RaisePropertyChanged("RegularBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OvertimeBurdenCost {
            get {
                return this.overtimeBurdenCostField;
            }
            set {
                this.overtimeBurdenCostField = value;
                this.RaisePropertyChanged("OvertimeBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DoubleTimeBurdenCost {
            get {
                return this.doubleTimeBurdenCostField;
            }
            set {
                this.doubleTimeBurdenCostField = value;
                this.RaisePropertyChanged("DoubleTimeBurdenCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
                this.RaisePropertyChanged("Fullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string UserBadgeID {
            get {
                return this.userBadgeIDField;
            }
            set {
                this.userBadgeIDField = value;
                this.RaisePropertyChanged("UserBadgeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Auth0Email {
            get {
                return this.auth0EmailField;
            }
            set {
                this.auth0EmailField = value;
                this.RaisePropertyChanged("Auth0Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Auth0Required {
            get {
                return this.auth0RequiredField;
            }
            set {
                this.auth0RequiredField = value;
                this.RaisePropertyChanged("Auth0Required");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ActiveDirectoryName {
            get {
                return this.activeDirectoryNameField;
            }
            set {
                this.activeDirectoryNameField = value;
                this.RaisePropertyChanged("ActiveDirectoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserPermissionsProfile {
            get {
                return this.userPermissionsProfileField;
            }
            set {
                this.userPermissionsProfileField = value;
                this.RaisePropertyChanged("UserPermissionsProfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public UserDefinedField[] UserDefinedFields {
            get {
                return this.userDefinedFieldsField;
            }
            set {
                this.userDefinedFieldsField = value;
                this.RaisePropertyChanged("UserDefinedFields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string RegularLaborAccountNumber {
            get {
                return this.regularLaborAccountNumberField;
            }
            set {
                this.regularLaborAccountNumberField = value;
                this.RaisePropertyChanged("RegularLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string OvertimeLaborAccountNumber {
            get {
                return this.overtimeLaborAccountNumberField;
            }
            set {
                this.overtimeLaborAccountNumberField = value;
                this.RaisePropertyChanged("OvertimeLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DoubleTimeLaborAccountNumber {
            get {
                return this.doubleTimeLaborAccountNumberField;
            }
            set {
                this.doubleTimeLaborAccountNumberField = value;
                this.RaisePropertyChanged("DoubleTimeLaborAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string LaborBurdenAccountNumber {
            get {
                return this.laborBurdenAccountNumberField;
            }
            set {
                this.laborBurdenAccountNumberField = value;
                this.RaisePropertyChanged("LaborBurdenAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DefaultScreen {
            get {
                return this.defaultScreenField;
            }
            set {
                this.defaultScreenField = value;
                this.RaisePropertyChanged("DefaultScreen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
                this.RaisePropertyChanged("MustChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public bool CannotChangePassword {
            get {
                return this.cannotChangePasswordField;
            }
            set {
                this.cannotChangePasswordField = value;
                this.RaisePropertyChanged("CannotChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool AccountDisabled {
            get {
                return this.accountDisabledField;
            }
            set {
                this.accountDisabledField = value;
                this.RaisePropertyChanged("AccountDisabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool Locator {
            get {
                return this.locatorField;
            }
            set {
                this.locatorField = value;
                this.RaisePropertyChanged("Locator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool SuspendLocator {
            get {
                return this.suspendLocatorField;
            }
            set {
                this.suspendLocatorField = value;
                this.RaisePropertyChanged("SuspendLocator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool CanSelectLocator {
            get {
                return this.canSelectLocatorField;
            }
            set {
                this.canSelectLocatorField = value;
                this.RaisePropertyChanged("CanSelectLocator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool CanSelectToVendorLot {
            get {
                return this.canSelectToVendorLotField;
            }
            set {
                this.canSelectToVendorLotField = value;
                this.RaisePropertyChanged("CanSelectToVendorLot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool ReceivingInspector {
            get {
                return this.receivingInspectorField;
            }
            set {
                this.receivingInspectorField = value;
                this.RaisePropertyChanged("ReceivingInspector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public bool TipOfDay {
            get {
                return this.tipOfDayField;
            }
            set {
                this.tipOfDayField = value;
                this.RaisePropertyChanged("TipOfDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool LargeButtons {
            get {
                return this.largeButtonsField;
            }
            set {
                this.largeButtonsField = value;
                this.RaisePropertyChanged("LargeButtons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool DisablePersistence {
            get {
                return this.disablePersistenceField;
            }
            set {
                this.disablePersistenceField = value;
                this.RaisePropertyChanged("DisablePersistence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public bool DefaultIncludeFuelActivity {
            get {
                return this.defaultIncludeFuelActivityField;
            }
            set {
                this.defaultIncludeFuelActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeFuelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool OnlyIncludeFuelActivity {
            get {
                return this.onlyIncludeFuelActivityField;
            }
            set {
                this.onlyIncludeFuelActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeFuelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool DefaultIncludeServiceActivity {
            get {
                return this.defaultIncludeServiceActivityField;
            }
            set {
                this.defaultIncludeServiceActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeServiceActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool OnlyIncludeServiceActivity {
            get {
                return this.onlyIncludeServiceActivityField;
            }
            set {
                this.onlyIncludeServiceActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeServiceActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool DefaultIncludePartSaleActivity {
            get {
                return this.defaultIncludePartSaleActivityField;
            }
            set {
                this.defaultIncludePartSaleActivityField = value;
                this.RaisePropertyChanged("DefaultIncludePartSaleActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public bool OnlyIncludePartSaleActivity {
            get {
                return this.onlyIncludePartSaleActivityField;
            }
            set {
                this.onlyIncludePartSaleActivityField = value;
                this.RaisePropertyChanged("OnlyIncludePartSaleActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public bool DefaultIncludeCateringActivity {
            get {
                return this.defaultIncludeCateringActivityField;
            }
            set {
                this.defaultIncludeCateringActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeCateringActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public bool OnlyIncludeCateringActivity {
            get {
                return this.onlyIncludeCateringActivityField;
            }
            set {
                this.onlyIncludeCateringActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeCateringActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public bool DefaultIncludeHotelActivity {
            get {
                return this.defaultIncludeHotelActivityField;
            }
            set {
                this.defaultIncludeHotelActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeHotelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public bool OnlyIncludeHotelActivity {
            get {
                return this.onlyIncludeHotelActivityField;
            }
            set {
                this.onlyIncludeHotelActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeHotelActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public bool DefaultIncludeTransportationActivity {
            get {
                return this.defaultIncludeTransportationActivityField;
            }
            set {
                this.defaultIncludeTransportationActivityField = value;
                this.RaisePropertyChanged("DefaultIncludeTransportationActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool OnlyIncludeTransportationActivity {
            get {
                return this.onlyIncludeTransportationActivityField;
            }
            set {
                this.onlyIncludeTransportationActivityField = value;
                this.RaisePropertyChanged("OnlyIncludeTransportationActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public bool LaunchLogbookResearch {
            get {
                return this.launchLogbookResearchField;
            }
            set {
                this.launchLogbookResearchField = value;
                this.RaisePropertyChanged("LaunchLogbookResearch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public bool CanEnterCompliance {
            get {
                return this.canEnterComplianceField;
            }
            set {
                this.canEnterComplianceField = value;
                this.RaisePropertyChanged("CanEnterCompliance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public bool IncludeAllDefaultLogbookSearchCriteria {
            get {
                return this.includeAllDefaultLogbookSearchCriteriaField;
            }
            set {
                this.includeAllDefaultLogbookSearchCriteriaField = value;
                this.RaisePropertyChanged("IncludeAllDefaultLogbookSearchCriteria");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementReferenceOutput : CorridorStatusData {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementChangePasswordInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementReferenceInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementCreatePermissionsProfileInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagemenAddOrUpdateData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementUpdateData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorLoginData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aliasNameField;
        
        private string loginIDField;
        
        private string loginPasswordField;
        
        private string sessionTokenField;
        
        private string auth0TokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
                this.RaisePropertyChanged("AliasName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
                this.RaisePropertyChanged("LoginID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LoginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                this.loginPasswordField = value;
                this.RaisePropertyChanged("LoginPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
                this.RaisePropertyChanged("SessionToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Auth0Token {
            get {
                return this.auth0TokenField;
            }
            set {
                this.auth0TokenField = value;
                this.RaisePropertyChanged("Auth0Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementChangePasswordInput : CorridorLoginData {
        
        private string usernameField;
        
        private string passwordField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementCreatePermissionsProfileInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementReferenceInput : CorridorLoginData {
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementCreatePermissionsProfileInput : UserManagementReferenceInput {
        
        private string createPermissionsProfileNameField;
        
        private bool setUserPermissionsProfileToNewField;
        
        public UserManagementCreatePermissionsProfileInput() {
            this.setUserPermissionsProfileToNewField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CreatePermissionsProfileName {
            get {
                return this.createPermissionsProfileNameField;
            }
            set {
                this.createPermissionsProfileNameField = value;
                this.RaisePropertyChanged("CreatePermissionsProfileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SetUserPermissionsProfileToNew {
            get {
                return this.setUserPermissionsProfileToNewField;
            }
            set {
                this.setUserPermissionsProfileToNewField = value;
                this.RaisePropertyChanged("SetUserPermissionsProfileToNew");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagemenAddOrUpdateData : UserManagementData {
        
        private string newUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NewUsername {
            get {
                return this.newUsernameField;
            }
            set {
                this.newUsernameField = value;
                this.RaisePropertyChanged("NewUsername");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementUpdateData : UserManagementData {
        
        private string newUsernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NewUsername {
            get {
                return this.newUsernameField;
            }
            set {
                this.newUsernameField = value;
                this.RaisePropertyChanged("NewUsername");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserManagementSoapChannel : API_TESTER_UI.UserManagement.UserManagementSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementSoapClient : System.ServiceModel.ClientBase<API_TESTER_UI.UserManagement.UserManagementSoap>, API_TESTER_UI.UserManagement.UserManagementSoap {
        
        public UserManagementSoapClient() {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public API_TESTER_UI.UserManagement.UserManagementReferenceOutput AddUser(API_TESTER_UI.UserManagement.UserManagementData userData) {
            return base.Channel.AddUser(userData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> AddUserAsync(API_TESTER_UI.UserManagement.UserManagementData userData) {
            return base.Channel.AddUserAsync(userData);
        }
        
        public API_TESTER_UI.UserManagement.UserManagementReferenceOutput UpdateUser(API_TESTER_UI.UserManagement.UserManagementUpdateData userData) {
            return base.Channel.UpdateUser(userData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> UpdateUserAsync(API_TESTER_UI.UserManagement.UserManagementUpdateData userData) {
            return base.Channel.UpdateUserAsync(userData);
        }
        
        public API_TESTER_UI.UserManagement.UserManagementReferenceOutput AddOrEditUserRequest(API_TESTER_UI.UserManagement.UserManagemenAddOrUpdateData userData) {
            return base.Channel.AddOrEditUserRequest(userData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> AddOrEditUserRequestAsync(API_TESTER_UI.UserManagement.UserManagemenAddOrUpdateData userData) {
            return base.Channel.AddOrEditUserRequestAsync(userData);
        }
        
        public API_TESTER_UI.UserManagement.UserManagementDataOutput GetUser(API_TESTER_UI.UserManagement.UserManagementReferenceInput userReference) {
            return base.Channel.GetUser(userReference);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementDataOutput> GetUserAsync(API_TESTER_UI.UserManagement.UserManagementReferenceInput userReference) {
            return base.Channel.GetUserAsync(userReference);
        }
        
        public API_TESTER_UI.UserManagement.UserManagementReferenceOutput ChangeUserPassword(API_TESTER_UI.UserManagement.UserManagementChangePasswordInput userPasswdData) {
            return base.Channel.ChangeUserPassword(userPasswdData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> ChangeUserPasswordAsync(API_TESTER_UI.UserManagement.UserManagementChangePasswordInput userPasswdData) {
            return base.Channel.ChangeUserPasswordAsync(userPasswdData);
        }
        
        public API_TESTER_UI.UserManagement.UserManagementReferenceOutput CreatePermissionsProfile(API_TESTER_UI.UserManagement.UserManagementCreatePermissionsProfileInput userCreateProfileData) {
            return base.Channel.CreatePermissionsProfile(userCreateProfileData);
        }
        
        public System.Threading.Tasks.Task<API_TESTER_UI.UserManagement.UserManagementReferenceOutput> CreatePermissionsProfileAsync(API_TESTER_UI.UserManagement.UserManagementCreatePermissionsProfileInput userCreateProfileData) {
            return base.Channel.CreatePermissionsProfileAsync(userCreateProfileData);
        }
    }
}
